Example 1.

In [1]:
import numpy as np

x = np.empty([3,2], dtype=int)

print(x)

[[2105042043 2105173115]
 [1545616672 1667330662]
 [ 757103227 2069789216]]


#### numpy.zeros

Example 2.

In [2]:
# array de zeros, por padrão é float

import numpy as np

x = np.zeros(5)

print(x)

[0. 0. 0. 0. 0.]


Example 3.

In [3]:
import numpy as np

x = np.zeros((5,), dtype=np.int)

print(x)

[0 0 0 0 0]


C:\Users\Caíque Miranda\AppData\Local\Temp\ipykernel_13828\1066040533.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.zeros((5,), dtype=np.int)


In [4]:
# zeros customizados

import numpy as np

x = np.zeros((2,2), dtype=[('x', 'i4'), ('y', 'i4')])

print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


#### numpy.ones

Example 4.

In [5]:
import numpy as np

x = np.ones(5)

print(x)

[1. 1. 1. 1. 1.]


Example 5.

In [6]:
import numpy as np

x = np.ones([2,2], dtype=int)

print(x)

[[1 1]
 [1 1]]


In [7]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

Author: Caique Miranda

Github username: caiquemiranda

numpy: 1.23.0
sys  : 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]



### End.