#### ndarray.shape

Esse atributo de matriz retorna uma tupla que consiste em dimensões de matriz. Também pode ser usado para redimensionar a matriz.

Example 1.

In [1]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])

print(a.shape)

(2, 3)


Example 2.

In [2]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])

a.shape=(3,2)

print(a)

[[1 2]
 [3 4]
 [5 6]]


Example 3.

In [3]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])

b = a.reshape(3,2)

print(b)

[[1 2]
 [3 4]
 [5 6]]


### ndarray.ndim

retorna o numero de dimensões do array

Example 4.

In [4]:
import numpy as np

a = np.arange(24)

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


Example 5.

In [5]:
# uma dimensão

import numpy as np

a = np.arange(24)

a.ndim

# agora reshape para mais dimensões

b = a.reshape(2,4,3)

print(b)

# b agora tem 3 dimensões

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


#### numpy.itemsize

Example 6.

In [6]:
import numpy as np

x = np.array([1,2,3,4,5], dtype=np.int8)

print(x.itemsize)

1


Example 7.

In [7]:
import numpy as np

x = np.array([1,2,3,4,5], dtype=np.float32)

print(x.itemsize)

4


#### numpy.flags

Example 8.

In [8]:
import numpy as np

x = np.array([1,2,3,4,5])

print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

