#### numpy.asarray

Example 1.

In [1]:
# convertendo listas em array

import numpy as np

x = [1,2,3]

a = np.asarray(x)

print(a)

[1 2 3]


Example 2.

In [2]:
import numpy as np

x = [1,2,3]

a = np.asarray(x, dtype=float)

print(a)

[1. 2. 3.]


Example 3.

In [3]:
# ndarray para tuplas

import numpy as np

x = (1,2,3)

a = np.asarray(x)

print(a)

[1 2 3]


Example 4.

In [4]:
# ndarray de lista para tupla

import numpy as np

x = [(1,2,3),(4,5)]

a = np.asarray(x)

print(a)

[(1, 2, 3) (4, 5)]


C:\Users\Caíque Miranda\AppData\Local\Temp\ipykernel_3772\357750122.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.asarray(x)


#### numpy.frombuffer

Example 5.

In [7]:
import numpy as np

s = 'Hello World'

a = np.frombuffer(s, dtype='S1')

print(a)

TypeError: a bytes-like object is required, not 'str'

#### numpy.fromiter

Example 6.

In [10]:
# criando lista usando range(f)

import numpy as np

list = range(5)

print(list)

range(0, 5)


Example 7.

In [11]:
import numpy as np

list = range(5)

it = iter(list)

x = np.fromiter(it, dtype=float)

print(x)

[0. 1. 2. 3. 4.]


### End.